
name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-16.04
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install build dependencies
      run: sudo apt-get install openjdk-8-jdk make gcc-4.7 gcc-4.7-plugin-dev gfortran-4.7 g++-4.7 gcc-4.7.multilib g++-4.7-multilib libz-dev

    - name: Download package sources
      run: cd tools && ./gradlew setupPackages

    # Workaround for https://github.com/bedatadriven/renjin-release/issues/3
    - name: Build Renjin GCC-Bridge Plugin
      run: cd renjin && ./gradlew tools:gcc-bridge:gcc-bridge-compiler:compilePlugin
 
    - name: Smoke test
      run: cd packages && ./gradlew checkTests -Ptestsuite=smoketest --continue -PrenjinHomeDir=$GITHUB_WORKSPACE/renjin/tools/gnur-installation/src/main/resources -PgccBridgePlugin=$GITHUB_WORKSPACE/renjin/tools/gcc-bridge/compiler/build/bridge.so

    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: logs
        path: packages/cran/*/build/*.log

